#! /bin/bash --norc
#produce executables once git repository cloned
#options compiler=intel, gfortran (default)
if [[ -z "$SMALIB_DIR" ]] ; then
   if [[ -z "$SMITER_DIR" ]] ; then
      #export SMALIB_DIR=../../smardda-lib/
      export SMALIB_DIR=$PWD
   else
      export SMALIB_DIR=${SMITER_DIR%/*}/smardda-lib
   fi
fi
echo "SMARDDA-LIB modules must lie under directory \$SMALIB_DIR = "$SMALIB_DIR
compiler1=intel
compiler2=intel_dbg
compiler3=gfortran
compiler4=gfortran_dbg
if [ "$1" == "$compiler1" ] ; then
    compiler=$compiler1
elif [ "$1" == "$compiler2" ] ; then
    compiler=$compiler2
elif [ "$1" == "$compiler3" ] ; then
    compiler=$compiler3
else
    compiler=$compiler4
fi
if [ -f $SMALIB_DIR/Extras/setup ] ; then
	source $SMALIB_DIR/Extras/setup
 	echo "you may want to add 'source "$SMALIB_DIR"/Extras/setup' to your .bashrc file"
else
	echo "Something is wrong - smardda-lib repository not cloned?"
	return
fi
if [ -f $SMALIB_DIR/../gwit/setup ] ; then
#give user access to gwit interface to git
	source $SMALIB_DIR/../gwit/setup
	echo "you may want to add 'source "$SMALIB_DIR"/../gwit/setup' to your .bashrc file"
fi

#ln -sf $SMALIB_DIR/config/config_"$compiler"_dbg.inc $SMALIB_DIR/config/config.inc
ln -sf $SMALIB_DIR/config/config_"$compiler".inc $SMALIB_DIR/config/config.inc

sed -e "s=SMALIB=$SMALIB_DIR=" <$SMALIB_DIR/config/path_generic.inc > $SMALIB_DIR/config/path.inc

#make sure executables are
chmod a+x $SMALIB_DIR/Extras/chmodx
$SMALIB_DIR/Extras/chmodx

#produce the fortran executables 
$SMALIB_DIR/exec/compile

cd $SMALIB_DIR/doc
echo "Warning - Documentation production requires doxygen at 1.8 or later"
doxygen doxyfile
if [  $? == 0 ] ; then 
  echo "to access documentation type firefox  or xdg-open $SMALIB_DIR/doc/srcdoc/html/index.html"
else
  echo "Looks like you didn't"
fi
cd $SMALIB_DIR
