#! /bin/bash --norc
swd=$PWD
if [[ -z "$SMALIB_DIR" ]] ; then
   if [[ ! -z "$SMITER_DIR" ]] ; then
      cd ${SMITER_DIR%/*}/smardda-lib
      export SMALIB_DIR=${SMITER_DIR%/*}/smardda-lib
   fi
else
   cd $SMALIB_DIR
fi
(cd fortd;make -j -f makefile > /dev/null 2>&1)
cd f95
ln -sf ../fortd LIB
for i in lib geofil move vtktfm datvtk hdsgen ctlgen parse; do make -j -f Makefile.Lib $i > /dev/null 2>&1 ;done
for i in geofil move vtktfm datvtk hdsgen ctlgen parse; do mv -f $i ../exec ;done
cd $swd
