# basic Makefile

# config file.
include ../config/config.inc
 
# Libraries
LIBS = 

SOURCES = \
parse.f90
 
PROG = parse

MODULES=$(SOURCES:.f90=.mod)

OBJECTS=$(SOURCES:.f90=.o)


$(PROG): $(OBJECTS) 
	$(F90) $(F90FLAGS) -o $(PROG) $(OBJECTS)  $(LIBS)

$(OBJECTS):$(MODULES)
	@touch .TOUCHFILE

$(MODULES): %.mod : %.f90
	$(F90) $(F90FLAGS) -c $<

clean:
	rm -f $(OBJECTS) *$(MOD) $(EXTRA_CLEAN_FILES)

distclean: clean
	rm -f $(PROG) 


.PHONY : clean distclean

