# basic Makefile

# config file.
include ../config/config.inc
 
# Libraries
LIBf90 = ./libsmardda$(DBG).a
LIBS = ./LIB/libsmarddalib$(DBG).a

SOURCES = \
beqan_h.f90 \
beqan_m.f90 \
beqart_h.f90 \
beqart_m.f90 \
beq_h.f90 \
beq_m.f90 \
bods_h.f90 \
bods_m.f90 \
btree_m.f90 \
ccontrol_m.f90 \
clock_m.f90 \
const_kind_m.f90 \
const_numphys_h.f90 \
control_h.f90 \
control_m.f90 \
date_time_m.f90 \
datline_h.f90 \
datline_m.f90 \
dbtree_h.f90 \
dbtree_m.f90 \
dcontrol_h.f90 \
dcontrol_m.f90 \
dfile_m.f90 \
edgprof_h.f90 \
edgprof_m.f90 \
fmesh_h.f90 \
fmesh_m.f90 \
geobjlist_h.f90 \
geobjlist_m.f90 \
geobj_m.f90 \
geofil_h.f90 \
geofil_m.f90 \
gfcontrol_h.f90 \
gfcontrol_m.f90 \
gfile_m.f90 \
hdsfile_m.f90 \
indict_m.f90 \
ld_m.f90 \
li_m.f90 \
log_h.f90 \
log_m.f90 \
ls_m.f90 \
mcontrol_h.f90 \
misc_m.f90 \
moutfile_m.f90 \
mtest_m.f90 \
nrsolve_m.f90 \
odes_h.f90 \
odes_m.f90 \
outfile_m.f90 \
pcle_h.f90 \
pcle_m.f90 \
pcontrol_h.f90 \
posang_h.f90 \
posang_m.f90 \
position_h.f90 \
position_m.f90 \
query_m.f90 \
scontrol_h.f90 \
scontrol_m.f90 \
smitermpi_h.f90 \
spl2d_m.f90 \
spl3d_m.f90 \
stack_m.f90 \
stlfile_m.f90 \
termplane_h.f90 \
vcontrol_h.f90 \
vcontrol_m.f90 \
vfile_m.f90 \
 
TGTS = geofil move vtktfm datvtk hdsgen ctlgen parse
 

MODULES=$(SOURCES:.f90=.mod)

OBJECTS=$(SOURCES:.f90=.o)

$(TGTS) : $(LIBf90) $(LIBS)
	$(F90) $(F90FLAGS) $@.f90 -o $@ $(LIBf90) $(LIBS)

lib $(LIBf90) : $(OBJECTS)
	@ar ru $(LIBf90) $(OBJECTS)

$(LIBS) :
	cd ./LIB && $(MAKE)

$(OBJECTS):$(MODULES)
	@touch .TOUCHFILE

$(MODULES): %.mod : %.f90
	$(F90) $(F90FLAGS) -c $<

clean:
	rm -f $(OBJECTS) *$(MOD) $(EXTRA_CLEAN_FILES)

distclean: clean
	rm -f  $(TGTS) $(LIBf90) $(LIBS)

libclean: clean
	rm -f  $(LIBf90)

txt:
	cat Makefile.lib $(SOURCES) > lib.txt

.PHONY : clean distclean libclean


beqan_h.f90 : const_kind_m.mod
beqan_h.f90 : const_numphys_h.mod
beqan_m.f90 : beqan_h.mod
beqan_m.f90 : log_m.mod
beqan_m.f90 : misc_m.mod
beqan_m.f90 : const_kind_m.mod
beq_h.f90 : const_kind_m.mod
beq_h.f90 : fmesh_h.mod
beq_h.f90 : spl2d_m.mod
beq_h.f90 : spl3d_m.mod
beq_h.f90 : beqart_h.mod
beq_m.f90 : const_kind_m.mod
beq_m.f90 : const_numphys_h.mod
beq_m.f90 : position_h.mod
beq_m.f90 : fmesh_h.mod
beq_m.f90 : beq_h.mod
beq_m.f90 : beqan_h.mod
beq_m.f90 : posang_h.mod
beq_m.f90 : position_m.mod
beq_m.f90 : log_m.mod
beq_m.f90 : misc_m.mod
beq_m.f90 : geobj_m.mod
beq_m.f90 : spl2d_m.mod
beq_m.f90 : spl3d_m.mod
beq_m.f90 : fmesh_m.mod
beq_m.f90 : posang_m.mod
beq_m.f90 : beqan_m.mod
beq_m.f90 : gfile_m.mod
beqart_h.f90 : const_kind_m.mod
beqart_h.f90 : fmesh_h.mod
beqart_m.f90 : const_kind_m.mod
beqart_m.f90 : const_numphys_h.mod
beqart_m.f90 : position_m.mod
beqart_m.f90 : posang_h.mod
beqart_m.f90 : log_m.mod
beqart_m.f90 : misc_m.mod
beqart_m.f90 : fmesh_h.mod
beqart_m.f90 : beqart_h.mod
beqart_m.f90 : beq_h.mod
beqart_m.f90 : fmesh_m.mod
beqart_m.f90 : vfile_m.mod
beqart_m.f90 : spl2d_m.mod
beqart_m.f90 : posang_m.mod
bods_h.f90 : const_kind_m.mod
bods_m.f90 : const_kind_m.mod
bods_m.f90 : log_m.mod
bods_m.f90 : const_numphys_h.mod
bods_m.f90 : bods_h.mod
bods_m.f90 : position_h.mod
bods_m.f90 : geobjlist_h.mod
bods_m.f90 : position_m.mod
bods_m.f90 : control_h.mod
bods_m.f90 : vcontrol_h.mod
bods_m.f90 : posang_h.mod
bods_m.f90 : ls_m.mod
bods_m.f90 : btree_m.mod
bods_m.f90 : geobj_m.mod
bods_m.f90 : query_m.mod
bods_m.f90 : posang_m.mod
bods_m.f90 : datline_h.mod
bods_m.f90 : datline_m.mod
bods_m.f90 : vfile_m.mod
bods_m.f90 : geobjlist_m.mod
btree_m.f90 : const_kind_m.mod
btree_m.f90 : log_m.mod
btree_m.f90 : control_h.mod
btree_m.f90 : position_h.mod
btree_m.f90 : position_m.mod
btree_m.f90 : geobj_m.mod
btree_m.f90 : query_m.mod
btree_m.f90 : ls_m.mod
ccontrol_m.f90 : const_kind_m.mod
ccontrol_m.f90 : log_m.mod
ccontrol_m.f90 : misc_m.mod
clock_m.f90 : const_kind_m.mod
clock_m.f90 : date_time_m.mod
clock_m.f90 : log_m.mod
const_numphys_h.f90 : const_kind_m.mod
control_h.f90 : const_kind_m.mod
control_h.f90 : position_h.mod
control_m.f90 : const_kind_m.mod
control_m.f90 : log_m.mod
control_m.f90 : misc_m.mod
control_m.f90 : position_h.mod
control_m.f90 : control_h.mod
control_m.f90 : position_m.mod
datline_h.f90 : const_kind_m.mod
datline_m.f90 : const_kind_m.mod
datline_m.f90 : log_m.mod
datline_m.f90 : datline_h.mod
dbtree_h.f90 : const_kind_m.mod
dbtree_h.f90 : position_h.mod
dbtree_h.f90 : ls_m.mod
dbtree_h.f90 : li_m.mod
dbtree_h.f90 : ld_m.mod
dbtree_m.f90 : const_kind_m.mod
dbtree_m.f90 : const_numphys_h.mod
dbtree_m.f90 : ls_m.mod
dbtree_m.f90 : btree_m.mod
dbtree_m.f90 : li_m.mod
dbtree_m.f90 : ld_m.mod
dbtree_m.f90 : dbtree_h.mod
dbtree_m.f90 : log_m.mod
dbtree_m.f90 : misc_m.mod
dbtree_m.f90 : position_h.mod
dbtree_m.f90 : geobjlist_h.mod
dbtree_m.f90 : position_m.mod
dbtree_m.f90 : geobj_m.mod
dcontrol_h.f90 : const_kind_m.mod
dcontrol_m.f90 : const_kind_m.mod
dcontrol_m.f90 : const_numphys_h.mod
dcontrol_m.f90 : log_m.mod
dcontrol_m.f90 : misc_m.mod
dcontrol_m.f90 : geobj_m.mod
dcontrol_m.f90 : dcontrol_h.mod
dfile_m.f90 : const_kind_m.mod
dfile_m.f90 : log_m.mod
dfile_m.f90 : misc_m.mod
dfile_m.f90 : datline_h.mod
dfile_m.f90 : datline_m.mod
edgprof_h.f90 : const_kind_m.mod
edgprof_m.f90 : edgprof_h.mod
edgprof_m.f90 : log_m.mod
edgprof_m.f90 : misc_m.mod
edgprof_m.f90 : const_numphys_h.mod
edgprof_m.f90 : const_kind_m.mod
edgprof_m.f90 : pcontrol_h.mod
fmesh_h.f90 : const_kind_m.mod
fmesh_h.f90 : position_h.mod
fmesh_m.f90 : position_h.mod
fmesh_m.f90 : fmesh_h.mod
fmesh_m.f90 : log_m.mod
fmesh_m.f90 : misc_m.mod
fmesh_m.f90 : const_kind_m.mod
fmesh_m.f90 : position_m.mod
geobjlist_h.f90 : const_kind_m.mod
geobjlist_h.f90 : position_h.mod
geobjlist_h.f90 : geobj_m.mod
geobjlist_m.f90 : const_kind_m.mod
geobjlist_m.f90 : log_m.mod
geobjlist_m.f90 : misc_m.mod
geobjlist_m.f90 : const_numphys_h.mod
geobjlist_m.f90 : position_h.mod
geobjlist_m.f90 : bods_h.mod
geobjlist_m.f90 : geobjlist_h.mod
geobjlist_m.f90 : position_m.mod
geobjlist_m.f90 : control_h.mod
geobjlist_m.f90 : vcontrol_h.mod
geobjlist_m.f90 : dcontrol_h.mod
geobjlist_m.f90 : posang_h.mod
geobjlist_m.f90 : ls_m.mod
geobjlist_m.f90 : btree_m.mod
geobjlist_m.f90 : li_m.mod
geobjlist_m.f90 : ld_m.mod
geobjlist_m.f90 : dbtree_h.mod
geobjlist_m.f90 : dbtree_m.mod
geobjlist_m.f90 : geobj_m.mod
geobjlist_m.f90 : query_m.mod
geobjlist_m.f90 : posang_m.mod
geobjlist_m.f90 : datline_h.mod
geobjlist_m.f90 : datline_m.mod
geobjlist_m.f90 : stack_m.mod
geobjlist_m.f90 : pcle_h.mod
geobjlist_m.f90 : pcle_m.mod
geobjlist_m.f90 : mtest_m.mod
geobjlist_m.f90 : indict_m.mod
geobjlist_m.f90 : vfile_m.mod
geobjlist_m.f90 : smitermpi_h.mod
geobj_m.f90 : const_kind_m.mod
geobj_m.f90 : const_numphys_h.mod
geobj_m.f90 : log_m.mod
geobj_m.f90 : position_h.mod
geobj_m.f90 : position_m.mod
geofil_h.f90 : const_kind_m.mod
geofil_h.f90 : geobjlist_h.mod
geofil_h.f90 : gfcontrol_h.mod
geofil_m.f90 : log_m.mod
geofil_m.f90 : misc_m.mod
geofil_m.f90 : const_numphys_h.mod
geofil_m.f90 : const_kind_m.mod
geofil_m.f90 : dcontrol_h.mod
geofil_m.f90 : dcontrol_m.mod
geofil_m.f90 : gfcontrol_h.mod
geofil_m.f90 : gfcontrol_m.mod
geofil_m.f90 : geofil_h.mod
geofil_m.f90 : geobj_m.mod
geofil_m.f90 : geobjlist_h.mod
geofil_m.f90 : geobjlist_m.mod
geofil_m.f90 : vfile_m.mod
geofil_m.f90 : indict_m.mod
gfcontrol_h.f90 : const_kind_m.mod
gfcontrol_m.f90 : const_kind_m.mod
gfcontrol_m.f90 : log_m.mod
gfcontrol_m.f90 : gfcontrol_h.mod
gfcontrol_m.f90 : geobj_m.mod
gfcontrol_m.f90 : misc_m.mod
gfile_m.f90 : const_kind_m.mod
gfile_m.f90 : log_m.mod
gfile_m.f90 : misc_m.mod
hdsfile_m.f90 : const_kind_m.mod
hdsfile_m.f90 : date_time_m.mod
hdsfile_m.f90 : log_m.mod
hdsfile_m.f90 : misc_m.mod
hdsfile_m.f90 : control_h.mod
hdsfile_m.f90 : btree_m.mod
hdsfile_m.f90 : geobjlist_h.mod
indict_m.f90 : const_kind_m.mod
indict_m.f90 : const_numphys_h.mod
indict_m.f90 : log_m.mod
ld_m.f90 : const_kind_m.mod
ld_m.f90 : log_m.mod
li_m.f90 : const_kind_m.mod
li_m.f90 : log_m.mod
log_m.f90 : const_kind_m.mod
log_m.f90 : date_time_m.mod
log_m.f90 : log_h.mod
log_m.f90 : smitermpi_h.mod
ls_m.f90 : const_kind_m.mod
ls_m.f90 : log_m.mod
ls_m.f90 : control_h.mod
mcontrol_h.f90 : const_kind_m.mod
mcontrol_h.f90 : position_h.mod
misc_m.f90 : const_kind_m.mod
misc_m.f90 : const_numphys_h.mod
misc_m.f90 : log_m.mod
moutfile_m.f90 : const_kind_m.mod
moutfile_m.f90 : log_m.mod
moutfile_m.f90 : misc_m.mod
moutfile_m.f90 : mcontrol_h.mod
moutfile_m.f90 : date_time_m.mod
mtest_m.f90 : const_kind_m.mod
mtest_m.f90 : const_numphys_h.mod
mtest_m.f90 : log_m.mod
mtest_m.f90 : control_h.mod
mtest_m.f90 : position_h.mod
mtest_m.f90 : position_m.mod
mtest_m.f90 : vfile_m.mod
mtest_m.f90 : geobjlist_h.mod
nrsolve_m.f90 : const_kind_m.mod
nrsolve_m.f90 : const_numphys_h.mod
nrsolve_m.f90 : log_m.mod
nrsolve_m.f90 : misc_m.mod
nrsolve_m.f90 : date_time_m.mod
nrsolve_m.f90 : spl2d_m.mod
nrsolve_m.f90 : pcontrol_h.mod
odes_h.f90 : const_kind_m.mod
odes_h.f90 : position_h.mod
odes_m.f90 : const_kind_m.mod
odes_m.f90 : const_numphys_h.mod
odes_m.f90 : log_m.mod
odes_m.f90 : spl2d_m.mod
odes_m.f90 : spl3d_m.mod
odes_m.f90 : odes_h.mod
odes_m.f90 : nrsolve_m.mod
outfile_m.f90 : const_kind_m.mod
outfile_m.f90 : log_m.mod
outfile_m.f90 : misc_m.mod
outfile_m.f90 : control_h.mod
outfile_m.f90 : date_time_m.mod
outfile_m.f90 : geobj_m.mod
outfile_m.f90 : ls_m.mod
outfile_m.f90 : geobjlist_h.mod
outfile_m.f90 : btree_m.mod
pcle_h.f90 : const_kind_m.mod
pcle_m.f90 : const_kind_m.mod
pcle_m.f90 : log_m.mod
pcle_m.f90 : const_numphys_h.mod
pcle_m.f90 : position_h.mod
pcle_m.f90 : pcle_h.mod
pcle_m.f90 : position_m.mod
pcle_m.f90 : control_h.mod
pcle_m.f90 : ls_m.mod
pcle_m.f90 : btree_m.mod
pcle_m.f90 : geobj_m.mod
pcle_m.f90 : query_m.mod
pcle_m.f90 : geobjlist_h.mod
pcle_m.f90 : termplane_h.mod
pcontrol_h.f90 : const_kind_m.mod
pcontrol_h.f90 : termplane_h.mod
posang_h.f90 : const_kind_m.mod
posang_m.f90 : const_kind_m.mod
posang_m.f90 : const_numphys_h.mod
posang_m.f90 : position_m.mod
posang_m.f90 : posang_h.mod
posang_m.f90 : log_m.mod
posang_m.f90 : position_h.mod
posang_m.f90 : fmesh_h.mod
posang_m.f90 : beq_h.mod
posang_m.f90 : spl2d_m.mod
position_h.f90 : const_kind_m.mod
position_m.f90 : const_kind_m.mod
position_m.f90 : log_m.mod
position_m.f90 : misc_m.mod
position_m.f90 : position_h.mod
position_m.f90 : smitermpi_h.mod
query_m.f90 : const_kind_m.mod
query_m.f90 : const_numphys_h.mod
query_m.f90 : log_m.mod
query_m.f90 : misc_m.mod
query_m.f90 : control_h.mod
query_m.f90 : position_h.mod
query_m.f90 : position_m.mod
scontrol_h.f90 : const_kind_m.mod
scontrol_m.f90 : const_kind_m.mod
scontrol_m.f90 : log_m.mod
scontrol_m.f90 : misc_m.mod
scontrol_m.f90 : scontrol_h.mod
smitermpi_h.f90 : const_kind_m.mod
spl2d_m.f90  : log_m.mod
vfile_m.f90 : const_kind_m.mod
vfile_m.f90 : log_m.mod
control_h.f90 : misc_m.mod
spl2d_m.f90 : position_m.mod
spl3d_m.f90 : spl2d_m.mod
vcontrol_m.f90 : scontrol_m.mod
odes_m.f90 : beqart_m.mod
stack_m.f90 : const_numphys_h.mod
stlfile_m.f90 : log_m.mod
stlfile_m.f90 : misc_m.mod
log_h.f90 : const_kind_m.mod
vcontrol_h.f90 : position_h.mod
stack_m.f90 : log_m.mod
vfile_m.f90 : misc_m.mod
beq_m.f90 : beqart_m.mod
