C
         SUBROUTINE INTERU(PRDX,KXT,PX,KLEFT,KPAD,KOFF,K)
C
C.WA REPLACES INTERV FOR UNIFORM NODAL DISTRIBUTION
C.WA WITH KOFF SPLINE OFFSET IN RANGE AND KPAD PADDING
         IP=PX*PRDX+KPAD
         KLEFT=MIN( MAX(IP-(KOFF-1),0), KXT-K ) + K
C        WRITE(*,*) 'INTERU', PRDX,KXT,PX,KLEFT,KPAD,KOFF,K
         RETURN
         END
