C
         SUBROUTINE MSRECT(PRCEN,PRMIN,PRMAX,PZCEN,PZMIN,PZMAX,PTHETA,
     +   PSMAX)
C
C     MAXIMUM DISTANCE FROM POINT TO EDGE OF RECTANGLE IN DIRECTION THETA.
C     POINT IS (RCEN,ZCEN)
C     RECTANGLE HAS OPPOSITE CORNERS (RMIN,ZMIN) AND (RMAX,ZMAX)
C     ***RESULT MAKES NO SENSE IF POINT LIES OUTSIDE RECTANGLE
         ZCOS=COS(PTHETA)
         ZSIN=SIN(PTHETA)
         IF (ZCOS.GT.0) THEN
            ZRD=PRMAX-PRCEN
         ELSE
            ZRD=PRCEN-PRMIN
         END IF
         IF (ZSIN.GT.0) THEN
            ZZD=PZMAX-PZCEN
         ELSE
            ZZD=PZCEN-PZMIN
         END IF
         IF (ABS(ZSIN).LT.1.E-8) ZSIN=1.E-8
         IF (ABS(ZCOS).LT.1.E-8) ZCOS=1.E-8
         PSMAX=MIN( ABS(ZRD/ZCOS), ABS(ZZD/ZSIN) )
         RETURN
         END
