C
         SUBROUTINE SPLEVAL(PFA,KN,PSIA,PSIB,PSI,PF,KCALL)
C
C     EVALUATE LINEAR SPLINE FIT ON UNIFORM SAMPLES
C     INPUT:
C     PFA ARE (KN+1) SAMPLE FUNCTION VALUES
C     PSIA IS VALUE OF PSI CORRESPONDING TO PFA(1)
C     PSIB IS VALUE OF PSI CORRESPONDING TO PFA(KN+1)
C     KCALL IS NON-ZERO INTEGER
C     OUTPUT:
C     PF INTERPOLATED VALUE OF PFA AT PSI
       DIMENSION   PFA(*)
       SAVE        ZSIG,     ZRDP,     ZARDP
       SAVE        IFIRST
       DATA        IFIRST/0/
C
         IF (IFIRST.NE.KCALL) THEN
C     TOGGLE SWITCH, IF KCALL CHANGES, RE-EVALUATE COEFFICIENTS
            IFIRST=KCALL
C
            ZSIG=SIGN(1.,PSIB-PSIA)
C     RECIPROCAL MESH-SPACING
            ZRDP=KN/(PSIB-PSIA)
            ZARDP=ABS(ZRDP)
C
         END IF
C
         CALL INTERU(ZARDP,KN,ZSIG*(PSI-PSIA),IP,1,2,1)
         ZDP=(PSI-PSIA)*ZRDP
         PF=(IP-ZDP)*PFA(IP)+(ZDP-IP+1)*PFA(IP+1)
         RETURN
         END
