#! /bin/bash
if [[ -z "$SMALIB_DIR" ]] ; then SMALIB_DIR=$HOME/smardda/smardda-lib; fi
extra=$SMALIB_DIR/Extras
rm -f obj2vtk.py
echo $* > obj2vtk.py
vim obj2vtk.py -S $extra/obj2vtk.ed
pvpython < obj2vtk.py
