#! /bin/bash
#smardda/smardda-lib specific setups
if [[ -z "$SMALIB_DIR" ]] ; then
    export SMALIB_DIR=$PWD
fi
export SMALIB_DOC=$SMALIB_DIR/doc/srcdoc/html
export PATH=$SMALIB_DIR/exec:$PATH
alias dd_doc="xdg-open $SMALIB_DOC/index.html" # doesn't always work
alias dd_doc="firefox $SMALIB_DOC/index.html"
export dd_doc
# Module handling
mcfound=n
uname -n | grep -q iter
# ITER hpc
if [ $? -eq 0 ] ; then
mcfound=y
module use /work/imas/etc/modulefiles
module load intel/12.0.2
export CC=icc
export CXX=icpc
export FC=ifort
export F90=ifort 
#module load python/2.7/9
module load qt/4.8.7
module load paraview/4.4.0
module use /work/imas/opt/EasyBuild/modules/all
module load GCC/4.8.3
module load dialog/1.2
module load flex
module load doxygen/1.8.8
module load gnuplot
#module load convert
module load texlive/2015
fi
uname -n | grep -q fuslw
if [ $? -eq 0 ] ; then
mcfound=y
#CCFE Scientific Linux
module load doxygen/1.8.9
module remove ifort
module load ifort/12.0.1.107
module load gnuplot/4.6.1
fi
uname -n | grep -q Latitude
if [ $? -eq 0 ] ; then
#nothing needed on laptop
mcfound=y
fi
uname -n | grep -q f8395
if [ $? -eq 0 ] ; then
#desktop linux
module load ifort/12.0
mcfound=y
fi
name -n | grep -q F8395
if [ $? -eq 0 ] ; then
#nothing needed on laptop
mcfound=y
fi
uname -n | grep -q DESKTOP-L49I1U5
if [ $? -eq 0 ] ; then
#nothing needed on laptop
mcfound=y
fi
if [ $mcfound == n ] ; then
  echo "No additional modules loaded - if needed, edit $SMALIB_DIR/Extras/setup"
fi
