#! /bin/bash
#smardda/smardda-lib specific setups
if [[ -z "$SMALIB_DIR" ]] ; then
    export SMALIB_DIR=$PWD
fi
export SMALIB_DOC=$SMALIB_DIR/doc/srcdoc/html
export PATH=$SMALIB_DIR/exec:$PATH
alias dd_doc="xdg-open $SMALIB_DOC/index.html" # doesn't always work
alias dd_doc="firefox $SMALIB_DOC/index.html"
export dd_doc
# Module handling
mcfound=n
uname -n | grep -q iter
# ITER hpc
if [ $? -eq 0 ] ; then
mcfound=y
. /usr/share/Modules/init/sh
#module purge # can undefine SMITER_DIR
module use /work/imas/etc/modulefiles
#module load flex/2.5.39
module load doxygen/1.8.8
if grep -q avx2 /proc/cpuinfo ; then
  module load iompi/2018a
else
  module load intel/17.0.4
  export MPDIR=/shared/libraries/mpi/mvapich2/2.3b-intel2017
  export PATH=${MPDIR}/bin:${PATH}
  export CPATH=${MPDIR}/include:${CPATH}
  export MANPATH=${MPDIR}/share/man:${MANPATH}
  export LD_LIBRARY_PATH=${MPDIR}/lib:${LD_LIBRARY_PATH}
  export PKG_CONFIG_PATH=${MPDIR}/lib/pkgconfig:${PKG_CONFIG_PATH}
  export MV2_ENABLE_AFFINITY=0 # 
fi
export F90=${F90:-mpif90} # uncomment for MPI build
module use /work/imas/opt/EasyBuild/modules/all
#module load Perl/5.20.3-goolf-1.5.16 # for latexmk to work
module load texlive/2015
# module load Java/1.8.0_162 # For MDSplus compilation
fi
uname -n | grep -q freia
if [ $? -eq 0 ] ; then
mcfound=y
#CCFE Scientific Linux
module load doxygen/1.8.9
module remove ifort
module load ifort/12.0.1.107
module load gnuplot/4.6.1
fi
uname -n | grep -q Latitude
if [ $? -eq 0 ] ; then
#nothing needed on laptop
mcfound=y
fi
uname -n | grep -q f8395
if [ $? -eq 0 ] ; then
#desktop linux
module load ifort/12.0
mcfound=y
fi
uname -n | grep -q F8395
if [ $? -eq 0 ] ; then
#nothing needed on Ubuntu for Windows
mcfound=y
fi
uname -n | grep -q DESKTOP-L49I1U5
if [ $? -eq 0 ] ; then
#nothing needed on Ubuntu for Windows
mcfound=y
fi
if [ $mcfound == n ] ; then
  echo "No additional modules loaded - if needed, edit $SMALIB_DIR/Extras/setup"
fi
