#! /bin/bash
if [[ -z "$SMALIB_DIR" ]] ; then SMALIB_DIR=$HOME/smardda/smardda-lib; fi
extra=$SMALIB_DIR/Extras
rm -f stl2vtk.py
echo $* > stl2vtk.py
vim stl2vtk.py -S $extra/stl2vtk.ed
pvpython < stl2vtk.py
