#! /bin/bash
if [[ -z "$SMALIB_DIR" ]] ; then SMALIB_DIR=$HOME/smardda/smardda-lib; fi
extra=$SMALIB_DIR/Extras
for i in $*; do
   rm -f vtkpngcl.py
   istr=${i%%.vtk}
   sed -e "s/PART/$istr/" < $extra/vtkpngcl_skel.py > vtkpngcl.py
   pvpython < vtkpngcl.py
done
